image: node:10.16.0

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
#  - test
  - publish
#
#eslint:
#  stage: test
#
#  script:
#    # Run eslint
#    - yarn run lint:js
#
#test:
#  stage: test
#
#  script:
#    - yarn run test:javascript
#    - yarn run test:typescript

publish:
  stage: publish

  script:
    - npm config set //registry.yarnpkg.com/:_authToken d85fdf8a-f9c9-4b0b-a196-68e01f453f04
    - PACKAGE_VERSION=$(node -pe "require('./package.json').version")
    - echo $PACKAGE_VERSION
    - yarn np $PACKAGE_VERSION --preview
  only:
    - master
