image: node:10.16.0

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - test

eslint:
  stage: test

  script:
    # Run eslint
    - yarn run lint:js

test:
  stage: test

  script:
    - yarn run test:javascript
    - yarn run test:typescript
