image: node:10.16.0

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - test
  - publish

eslint:
  stage: test

  script:
    # Run eslint
    - yarn run lint:js


test javascript:
  stage: test

  script:
    - yarn run test:javascript

test typeascript:
  stage: test

  script:
    - yarn run test:typescript

publish:
  stage: publish

  script:
    - PACKAGE_VERSION==$(node -pe "require('./package.json').version")
    - echo $PACKAGE_VERSION
    - np $PACKAGE_VERSION --preview
