variables:
  #fallback value overwritten by CI variable
  NODE_CI_IMAGE: "node:12.16.3"

image: $NODE_CI_IMAGE


cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - test

eslint:
  stage: test

  script:
    # Run eslint
    - yarn run lint:js
  interruptible: true

test:
  stage: test

  script:
    - yarn run test:javascript
    - yarn run test:typescript
  interruptible: true
